SELECT VIOLATION_DATE, SUM(Num_Violations) AS Total_violations
FROM Violations
WHERE SUBSTR(VIOLATION_DATE, 1, 5) = '07/04' 
AND CAST(SUBSTR(Violation_Date, 7, 4) AS INTEGER) BETWEEN 2014 AND 2024
GROUP BY Violation_Date
ORDER BY CAST(SUBSTR(Violation_Date, 7, 4) AS INTEGER) ASC